from app.models.models import (
    User,
    Project,
    Skill,
    Experience,
    ResearchPaper,
    Achievement,
    ContactMessage,
    BlogPost,
    SocialLink,
    SiteSetting,
    Education,
    Certification,
    MediaAsset,
    TechnicalEvent,
)
